app/BearCamp/BearCamp/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BearEF;
using BearCommon;

namespace BearCamp.Controllers
{
    public class DonationController : Controller
    {
        private bearcampEntities db = new bearcampEntities();

        //
        // GET: /Donation/

        public ViewResult Index()
        {
            return View(db.Donations.ToList());
        }

        //
        // GET: /Donation/Details/5

        public ViewResult Details(int id)
        {
            Donation donation = db.Donations.Find(id);
            return View(donation);
        }

        //
        // GET: /Donation/Create

        public ActionResult Create()
        {
            //ViewBag.DonationType = new SelectList(db.DonationTypeIDs, "DonationTypeID1", "DonationDesc");
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "FastName");
            return View();
        }


        public ActionResult ExportDonations()
        {
            if (ModelState.IsValid)
            {
                var export = new DonationsExport();
                //string sConn = ConfigurationManager.ConnectionStrings["export2csvConn"].ToString();

                export.ExportCsv();


                //db.Users.Add(user);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return Redirect("/Donors"); //View(db.Users.ToList());
        }

        //
        // POST: /Donation/Create

        [HttpPost]
        public ActionResult Create(Donation donation)
        {
            if (ModelState.IsValid)
            {
                db.Donations.Add(donation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.DonationType = new SelectList(db.DonationTypeIDs, "DonationTypeID1", "DonationDesc", donation.DonationType);
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "FastName", donation.DonorID);
            return View(donation);
        }

        //
        // GET: /Donation/Edit/5

        public ActionResult Edit(int id)
        {
            Donation donation = db.Donations.Find(id);
            //ViewBag.DonationType = new SelectList(db.DonationTypeIDs, "DonationTypeID1", "DonationDesc", donation.DonationType);
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "FastName", donation.DonorID);
            return View(donation);
        }

        //
        // POST: /Donation/Edit/5

        [HttpPost]
        public ActionResult Edit(Donation donation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.DonationType = new SelectList(db.DonationTypeIDs, "DonationTypeID1", "DonationDesc", donation.DonationType);
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "FastName", donation.DonorID);
            return View(donation);
        }

        //
        // GET: /Donation/Delete/5

        public ActionResult Delete(int id)
        {
            Donation donation = db.Donations.Find(id);
            return View(donation);
        }

        //
        // POST: /Donation/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Donation donation = db.Donations.Find(id);
            db.Donations.Remove(donation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

app/BearCamp/BearCamp/Controllers/DonorsController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using BearEF;
using System.Configuration;
using BearCommon;

namespace BearCamp.Controllers
{
    public class DonorsController : BaseController
    {

        //
        // GET: /Donors/
        [Authorize]
        public ViewResult Index()
        {
            return View(Db.Donors.ToList());
        }

        //
        // GET: /Donors/Details/5
        [Authorize]
        public ViewResult Details(int id)
        {
            Donor donor = Db.Donors.Find(id);
            return View(donor);
        }

        //
        // GET: /Donors/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult ExportUsers()
        {
            if (ModelState.IsValid)
            {
                var export = new UserExport();
                //string sConn = ConfigurationManager.ConnectionStrings["export2csvConn"].ToString();

                export.ExportCsv();


                //db.Users.Add(user);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return Redirect("/Donors"); //View(db.Users.ToList());
        }
    
        //
        // POST: /Donors/Create


        [HttpPost]
        public ActionResult Create(Donor donor)
        {
            if (ModelState.IsValid)
            {
                Db.Donors.Add(donor);
                Db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(donor);
        }
        
        //
        // GET: /Donors/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            Donor donor = Db.Donors.Find(id);
            return View(donor);
        }

        //
        // POST: /Donors/Edit/5

        [HttpPost]
        public ActionResult Edit(Donor donor)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(donor).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donor);
        }

        //
        // GET: /Donors/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            Donor donor = Db.Donors.Find(id);
            return View(donor);
        }

        //
        // POST: /Donors/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Donor donor = Db.Donors.Find(id);
            Db.Donors.Remove(donor);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            Db.Dispose();
            base.Dispose(disposing);
        }
    }
}

app/BearCamp/BearCamp/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BearEF;

namespace BearCamp.Controllers
{ 
    public class PermissionController : Controller
    {
        private bearcampEntities db = new bearcampEntities();

        //
        // GET: /Permission/

        public ViewResult Index()
        {
            var permissions = db.Permissions.Include(p => p.Feature).Include(p => p.User);
            return View(permissions.ToList());
        }

        //
        // GET: /Permission/Details/5

        public ViewResult Details(int id)
        {
            Permission permission = db.Permissions.Find(id);
            return View(permission);
        }

        //
        // GET: /Permission/Create

        public ActionResult Create()
        {
            ViewBag.FeatureID = new SelectList(db.Features, "FeatureID", "FeatureName");
            ViewBag.UserLogin = new SelectList(db.Users, "UserLogin", "Pswd");
            return View();
        } 

        //
        // POST: /Permission/Create

        [HttpPost]
        public ActionResult Create(Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Permissions.Add(permission);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.FeatureID = new SelectList(db.Features, "FeatureID", "FeatureName", permission.FeatureID);
            ViewBag.UserLogin = new SelectList(db.Users, "UserLogin", "Pswd", permission.UserLogin);
            return View(permission);
        }
        
        //
        // GET: /Permission/Edit/5
 
        public ActionResult Edit(int id)
        {
            Permission permission = db.Permissions.Find(id);
            ViewBag.FeatureID = new SelectList(db.Features, "FeatureID", "FeatureName", permission.FeatureID);
            ViewBag.UserLogin = new SelectList(db.Users, "UserLogin", "Pswd", permission.UserLogin);
            return View(permission);
        }

        //
        // POST: /Permission/Edit/5

        [HttpPost]
        public ActionResult Edit(Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FeatureID = new SelectList(db.Features, "FeatureID", "FeatureName", permission.FeatureID);
            ViewBag.UserLogin = new SelectList(db.Users, "UserLogin", "Pswd", permission.UserLogin);
            return View(permission);
        }

        //
        // GET: /Permission/Delete/5
 
        public ActionResult Delete(int id)
        {
            Permission permission = db.Permissions.Find(id);
            return View(permission);
        }

        //
        // POST: /Permission/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Permission permission = db.Permissions.Find(id);
            db.Permissions.Remove(permission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

app/BearCamp/BearCamp/Controllers/UserController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using BearEF;



namespace BearCamp.Controllers
{ 
    public class UserController : Controller
    {
        private bearcampEntities db = new bearcampEntities();

        //
        // GET: /User/

        public ViewResult Index()
        {
            return View(db.Users.ToList());
        }

        //
        // GET: /User/Details/5

        public ViewResult Details(string id)
        {
            User user = db.Users.Find(id);
            return View(user);
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /User/Create



       


        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(user);
        }
        
        //
        // GET: /User/Edit/5
 
        public ActionResult Edit(string id)
        {
            User user = db.Users.Find(id);
            return View(user);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        //
        // GET: /User/Delete/5
 
        public ActionResult Delete(string id)
        {
            User user = db.Users.Find(id);
            return View(user);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {            
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

app/BearCamp/BearCamp/Views/Shared/_DonationLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>_DonationLayout</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

app/BearCamp/BearCamp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Bear Camp</title>
    <link href="@Url.Content("~/Content/styles.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css"/>
    <script src="@Url.Content("/Scripts/jquery-1.8.2.min.js")"type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3-respond-1.1.0.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
           
            <div id="logindisplay" class="btn">
                @Html.Partial("_LogOnPartial")
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                         <a class="brand" href="#"> <img src="../../Content/images/bearsmall.png"/></a>
                        <ul class="nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @if (HttpContext.Current.User.Identity.IsAuthenticated)
                            {
                                <li class="dropdown">
                                    <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Donors <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                                        <li>@Html.ActionLink("Donor List", "Index", "Donors")</li>
                                        <li>@Html.ActionLink("Add Donor", "Create", "Donors")</li>
                                    </ul>
                                </li> 
                                <li class="dropdown">
                                    <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                                        <li>@Html.ActionLink("Users List", "Index", "User")</li>
                                        <li>@Html.ActionLink("Add Users", "Create", "User")</li>
                                        <li>@Html.ActionLink("Manage Roles", "Index", "Permission")</li>
                                    </ul>
                                </li> 
                                <li class="dropdown">
                                    <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Donations <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                                        <li>@Html.ActionLink("Add Donation", "Create", "Donation")</li>
                                        <li>@Html.ActionLink("Donation List", "Index", "Donation")</li>
                                        <li>@Html.ActionLink("Add Donation Type", "Create", "DonationType")</li>
                                        <li>@Html.ActionLink("Donation Type List", "Index", "DonationType")</li>

                                    </ul>
                                </li>
                          
                            }
                        </ul>

                    </div>
                </div>
            </div>
 
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

app/BearCamp/BearCamp/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    @Html.ActionLink("Log Off", "LogOff", "Account") </text>
}
else {
    @: @Html.ActionLink("Log On", "LogOn", "Account") 
}